<?php

function rebeca_colfuturo_menu() {
    $items['rebeca/buscador'] = array(
    'title' => 'Buscador Rebeca',
    'page callback' => '_search_rebeca_content',
    'access callback' => TRUE,
    );

    return $items;
  }


function _search_rebeca_content(){

return drupal_render(drupal_get_form('rebeca_colfuturo_dependent_dropdown1')).
                '<div id="bSearchResults">
                      <div>
                        <h3 class="subtitulo-seccion-rojo">Listando todas las publicaciones</h3>
                      </div>
                      <div class="respuesta">
                      </div>
                </div>';
}


function rebeca_colfuturo_dependent_dropdown1($form, &$form_state){

  $options_first = _ajax_get_first_dropdown_options();
  $selected = isset($form_state['values']['dropdown_first']) ? $form_state['values']['dropdown_first'] : key($options_first);

          $form['dropdown_first'] = array(
            '#type' => 'select',
            '#title' => 'Filtrar Por:',
            '#options' => $options_first,
            '#default_value' => $selected,
            '#ajax' => array(
              'callback' => 'ajax_dependent_dropdown_callback',
              'wrapper' => 'dropdown-second-replace',
            ),
          );

          $form['dropdown_second'] = array(
              '#type' => 'select',
              '#title' => $options_first[$selected] . ' ' . t(''),
              '#prefix' => '<div id="dropdown-second-replace">',
              '#suffix' => '</div>',
              '#options' => _ajax_get_second_dropdown_options($selected),
              '#default_value' => isset($form_state['values']['dropdown_second']) ? $form_state['values']['dropdown_second'] : '',
          );
        return $form;
} // end function  rebeca_colfuturo_dependent_dropdown1

function ajax_dependent_dropdown_callback($form, $form_state) {
  return $form['dropdown_second'];
}


function _ajax_get_first_dropdown_options(){

  $arrayopc = array('div#edit-field-ano-de-publicacion-value-wrapper' => 'Año Publicacion',
                    'div#edit-field-autor-value-wrapper' => 'Autor',
                    'div#edit-field-editorial-value-wrapper' => 'Editorial',
                    'div#edit-field-lugar-de-publicacion-tid-wrapper' => 'Lugar de publicación',
                    'div#edit-field-subtema-tid-1-wrapper' => 'Subtema',
                    'div#edit-field-tema-tid-wrapper' => 'Tema',
                    'div#edit-title-wrapper' => 'Titulo',
                    'div#edit-field-tipo-de-material-tid-1-wrapper' => 'Tipo de Material',
                    );

  return $arrayopc;

}


function _ajax_get_second_dropdown_options($key) {


$options = drupal_map_assoc(
    array(
      t('--Seleccione--'),
      t('Todos'),
      t('Subtema'),
      t('Tema'),
      t('Titulo'),
      t('Año Publicacion'),
      t('Autor'),
      t('Editorial'),
      t('Lugar de Publicación'),
      t('Tipo de material'),
    )
  );

unset($options[$key]);

 return $options;
}


function _result_search_rebeca_content($form, &$form_state){

  $dropdown_first  =  $form_state['values']['dropdown_first'];
  $dropdown_second = $form_state['values']['dropdown_second'];


  $output = result_serch_content_rebeca($dropdown_first,$dropdown_second);


  //$output = search_json_process($busqueda);
  $commands[] = ajax_command_html(".respuesta",$output);
  $return = array('#type' => 'ajax', '#commands' => $commands);

  return $return;
}


function result_serch_content_rebeca($dropdown_first,$dropdown_second){


  return $dropdown_first;

}


function rebeca_colfuturo_form_alter(&$form, &$form_state, $form_id){


  //dpm($form);

  if ( $form['#id'] == 'views-exposed-form-biblioteca-rebeca-page' ){

      $path = drupal_get_path('module','rebeca_colfuturo');
      drupal_add_js($path."/src/js/form.js",'file' );
      drupal_add_css($path."/src/css/form.css",'file' );

      $selected = isset($form_state['values']['dropdown_first']) ? $form_state['values']['dropdown_first'] : key($options_first);

      $options_first = _ajax_get_first_dropdown_options();
      $form['dropdown_first'] = array(
            '#attributes' => array( 'class' => array('select_filter')),
            '#type' => 'select',
            '#title' => 'Filtrar Por:',
            '#options' => $options_first,
            '#default_value' => $selected,
          );

      $form['more'] = array(
      '#markup' => '<div><div class="more-input"></div></div>'
      );

    }

}


